### ISSUE TITLE
Installaltion problem

### ISSUE THREAD

**Issue by akentphonon** [MaterialsDiscovery/PyChemia#14]
Dear Developers,

I am trying to install pychemia by 

pip3 install pychemia --user

But it fails with following errors. Any help is appreciated. 

   ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-rd5hvw21/pychemia/setup.py", line 141, in <module>
        data = write_version_py()
      File "/tmp/pip-install-rd5hvw21/pychemia/setup.py", line 89, in write_version_py
        release_data, FULLVERSION, GIT_REVISION = get_version_info()
      File "/tmp/pip-install-rd5hvw21/pychemia/setup.py", line 47, in get_version_info
        rf = open('setup.json')
    FileNotFoundError: [Errno 2] No such file or directory: 'setup.json'
    Using Cython: True
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-rd5hvw21/pychemia/

Thanks,

Best
\Alex

**Comment by akentphonon** [comment]
Problem solved.. the issue was with the develop branch.
